### ISSUE TITLE
Input file problem

### ISSUE THREAD

**Issue by kateryna-goloviznina** [paduagroup/clandpol#12]
@agiliopadua 

Traceback (most recent call last):
  File "polarizer.py", line 1243, in <module>
    main()
  File "polarizer.py", line 1237, in main
    data.lmpscript(drude, args.outdfile, args.thole, args.cutoff)
  File "polarizer.py", line 617, in lmpscript
    with open(inpstack, 'x') as f:
ValueError: mode string must begin with one of 'r', 'w', 'a' or 'U', not 'x'

I will fix it.

**Comment by kateryna-goloviznina** [comment]
Solved.

**Comment by agiliopadua** [comment]
Funny, works on my python… it’s great compared to w because it gives an error if the file exists.
Agilio

**Comment by kateryna-goloviznina** [comment]
@agiliopadua It works only with python3.
