### ISSUE TITLE
Counting H in water

### ISSUE THREAD

**Issue by kateryna-goloviznina** [paduagroup/clandpol#15]
Polarizer and scaleLJ consider the unique value of hydrogen polarisability. When working with water, the hydrogen polarizability of 0.323 is not correct.
We can either modify scripts to treat water as an exception and keep
```
ODw     0.8    -1.7164  4184.0   0.978   2.6
Hw      0.0     0.0000  4184.0   0.000   2.6
```
(if mass = 0.8 than this atom type is polarisable water - > ignore counting H)
or apply the same approach we are using and subtract hydrogen polarisability from 0.978 
```
ODw     0.8    -1.7164  4184.0   0.332   2.6
Hw      0.0     0.0000  4184.0   0.323   2.6  
```
@agiliopadua what do you prefer? I will do all the changes in the code by myself if you like the first variant.

**Comment by agiliopadua** [comment]
I much prefer the second, which goes for generality.

**Comment by kateryna-goloviznina** [comment]
Ok, thank you!
