### ISSUE TITLE
Clarification on usage

### ISSUE THREAD

**Issue by arm61** [paduagroup/clandpol#19]
Thanks for sharing this great resource. I just wanted to clarify the usage. Am I correct that running a LAMMPS simulation with the `in.lmp` file that is produced does **not** include any polarisation and it is necessary to add the lines from `in-drude.lmp` to the `in.lmp` to "activate" polarisation?

**Comment by agiliopadua** [comment]
Yes. Some of the lines in `in-drude.lmp` contain new commands to add, other show changes to commands already in the original `in.lmp`. It's important to understand what each command does, so read the comments attentively.

**Comment by arm61** [comment]
Great. That's what I thought. Many thanks!
