### ISSUE TITLE
Problem working through example in Readme

### ISSUE THREAD

**Issue by william-pfalzgraff** [paduagroup/clandpol#3]
Hi there,
I  read and enjoyed your recent JCTC paper on the CL&Pol force field and I am interested in reproducing your work.  I appreciate you making the parameters and code that generates input files available!

I am working through your tutorial and unfortunately I obtain the following error at step 2, when using the polarizer.py script:

```
$ python polarizer.py c4c1im.zmat dca.zmat -f alpha.ff -q -id data.lmp -od data-p.lmp
  error: atom type C1 has different number of hydrogens attached in structure files
```

Do you have any advice on how to proceed?  I am able to work through the example provided for setting up non-polarizable simulations with the fftool repo [here](https://github.com/agiliopadua/fftool), so I believe I am doing step 1 correctly. 

Thanks very much for your help!
Will Pfalzgraff

**Comment by kateryna-goloviznina** [comment]
Hello,
We appreciate that you are interested in using CL&Pol force field! 

As it is mentioned in our paper, hydrogen atoms are not polarisable and their polarisability is merged into polarisability of the neighboring atom. This error means that there are two C1 atoms with different numbers of hydrogens attached, but the script requires a constant number of H for each atomic type.

In the original non-polarisable CL&P force field, C1 atom type corresponds to any C atom directly attached to NA atoms of the imidazolium ring, so C1 of CH3 group and C1 of C4H10 are identical. In the CL&Pol we kept C1 atom type for methyl group and introduced C1A type for any other longer side chain:

<img src="https://user-images.githubusercontent.com/44566999/89190478-d187a480-d5a1-11ea-8533-cb340aeca4a9.png" width="40%">

In c4c1im.zmat file of the pol-il/example folder we replaced C1 of the butyl chain by C1A one. However, we did not modify the files in fftool folder, so if you are using those ones, you need to modify them by yourself.

Feel free to contact us if you have any other questions.

Best wishes,
Kateryna

**Comment by william-pfalzgraff** [comment]
That helps!  Thank you for the explanation.
