### ISSUE TITLE
Pair-Drude file

### ISSUE THREAD

**Issue by kateryna-goloviznina** [paduagroup/clandpol#9]
@agiliopadua, do we actually need a separate pair-drude.lmp file if the pair_coff are included to pair-p.lmp anyway?

**Comment by agiliopadua** [comment]
No

**Comment by kateryna-goloviznina** [comment]
I will remove it and write all the pair_coeff directly to pair-p.lmp.

**Comment by agiliopadua** [comment]
I've made my mind on this.
I think it is simpler just to write the new terms for the drude particles as in the old version.
